; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nodemcu-32s                           ; 默认编译环境

[env:nodemcu-32s]
platform = espressif32                               ; 使用ESP32平台
board = nodemcu-32s                                  ; 开发板型号
framework = arduino                                  ; 使用Arduino框架
upload_speed = 1000000                              ; 上传速率（波特率）
monitor_speed = 115200                              ; 串口监视器波特率
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43                         ; TFT显示屏驱动库
	lvgl/lvgl@^9.0.0                                ; LVGL图形库
	bblanchon/ArduinoJson @ ^6.21.3                 ; JSON库
    lennarthennigs/Button2@^2.2.4                   ; 按钮处理库
    knolleary/PubSubClient @ ^2.8.0                 ; MQTT客户端库
build_flags = 
    ; -I src/config                                   ; 包含配置文件目录
    -I ./include                                    ; 包含配置文件目录
    -D LV_LVGL_H_INCLUDE_SIMPLE

	-D USER_SETUP_LOADED                            ; 使用用户自定义配置
	-D ST7789_DRIVER                                ; 显示屏驱动类型
	-D TFT_WIDTH=240                                ; 显示屏宽度
	-D TFT_HEIGHT=240                               ; 显示屏高度
	-D TFT_MOSI=17                                  ; SDA引脚
	-D TFT_SCLK=18                                  ; SCL引脚
	-D TFT_DC=5                                     ; 数据/命令控制引脚
	-D TFT_RST=19                                   ; 复位引脚
	-D TFT_BL=22                                    ; 背光控制引脚
	-D TOUCH_CS=-1                                  ; 触摸芯片选择引脚
	-D SPI_FREQUENCY=27000000                       ; SPI通信频率

    ; 小米手机wifi
	; -D WIFI_SSID=\"Mi\"                          ; WiFi名称
	; -D WIFI_PASSWORD=\"12345678\"                ; WiFi密码
    ; 小米路由器wifi
    -D WIFI_SSID=\"Redmi_016C\"                    ; WiFi名称
	-D WIFI_PASSWORD=\"87654321\"                  ; WiFi密码

    
    -Os                                             ; 优化大小
    -DCORE_DEBUG_LEVEL=0                            ; 关闭调试输出
    -ffunction-sections                             ; 未使用的函数放入单独段
    -fdata-sections                                 ; 未使用的数据放入单独段
    ; 移除 -flto              ; 删除 LTO 优化
    -Wl,--print-memory-usage                       ; 添加内存使用报告

; 链接优化
; build_unflags = -Os

extra_scripts = 
    scripts/publish.py
    ; pre:scripts/remove_unused_sections.py

build_src_filter = 
    +<*>                    ; 包含所有源文件
    -<3D/>                  ; 排除3D目录
    -<doc/>                 ; 排除文档
    -<test/>               ; 排除测试
    -<scripts/>            ; 排除脚本
    -<partitions/>         ; 排除分区文件
    -<*.md>               ; 排除markdown文件
    -<*.drawio>           ; 排除绘图文件
    -<.pio/>               ; 排除pio目录
    -<.git/>               ; 排除git目录
    -<.vscode/>            ; 排除vscode目录

board_build.partitions = partitions/custom_ota.csv  ; 使用custom_ota分区表


[env:native]
platform = native@^1.1.3                            ; 本地测试平台
framework =                                         ; 无框架依赖
lib_deps = 
	googletest                                      ; Google测试框架
